import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body className="flex flex-col min-h-screen">
        {/* Top Navbar */}
        <header className="sticky top-0 z-50 glass border-b border-white/20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              {/* Logo */}
              <div className="flex-shrink-0 flex items-center">
                <Link href="/" className="text-xl font-bold text-slate-800">
                  ⚡ Hotel PMS
                </Link>
              </div>
              
              {/* Desktop Menu */}
              <nav className="hidden md:flex space-x-6">
                <Link href="/" className="text-slate-600 hover:text-blue-600 font-medium">Dashboard</Link>
                <Link href="/reports" className="text-slate-600 hover:text-blue-600 font-medium">Reports</Link>
                <Link href="/energy" className="text-slate-600 hover:text-blue-600 font-medium">Energy</Link>
                <Link href="/bookings" className="text-slate-600 hover:text-blue-600 font-medium">Booking</Link>
                <Link href="/checkin" className="text-slate-600 hover:text-blue-600 font-medium">Check-in</Link>
                <Link href="/settings" className="text-blue-600 font-semibold border-b-2 border-blue-600">Settings</Link>
              </nav>
              
              {/* Mobile Menu Button (Placeholder) */}
              <div className="md:hidden flex items-center">
                <button className="text-slate-500 hover:text-slate-700">
                  <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-1 w-full max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
